name: CI (Java A*)

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Compile
        run: javac src/*.java
      - name: Run test
        run: java -cp src Main <<EOF
5
30
1 3 6 8 12
EOF
